<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>MooseX-Declare</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.perl.moose.declare</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.perl.moose.declare</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(namespace)\s+(\S+)\b</string>
			<key>name</key>
			<string>meta.namespace.perl.moose.declare</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.perl.moose.declare</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.perl.moose.declare</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(role)\s+(\S+)\b</string>
			<key>name</key>
			<string>meta.role.perl.moose.declare</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.perl.moose.declare</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.perl.moose.declare</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(class)\s+(\S+)\b</string>
			<key>name</key>
			<string>meta.class.perl.moose.declare</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.method.perl.moose.declare</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.perl.moose.declare</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.method.perl.moose.declare</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((?:multi\s+)?method)\s+([-a-zA-Z0-9_]+)\s*(\(.*\))?</string>
			<key>name</key>
			<string>meta.method.perl.moose.declare</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.perl.moose</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.perl.moose.declare</string>
	<key>uuid</key>
	<string>0CF5AB7D-45A1-4E74-A9EC-8AD2F791DCE9</string>
</dict>
</plist>
